#!/bin/bash
#SBATCH --job-name=xmetavat-test
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH -o xt.%j.out
#SBATCH -e xt.%j.err

source ~/.bashrc

docker run --rm \
  -v "/localpath/to/rawdata:/pipeline/rawdata:ro" \
  -v "/localpath/to/results:/pipeline/results:rw" \
  -v "/localpath/to/config.yaml:/pipeline/config.yaml:ro" \
  -v "/localpath/to/samples.tsv:/pipeline/samples.tsv:ro" \
  -v "/localpath/to/database:/pipeline/database:rw" \
  xmetavar:1.0.0 all --cores 16
